name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./todo_app
      run: npm install

    - name: Run tests
      working-directory: ./todo_app
      run: npm test

    - name: Build project
      working-directory: ./todo_app
      run: npm run build

    - name: Check code quality
      working-directory: ./todo_app
      run: npm run lint

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deployment placeholder
      run: echo "Deploy your app here"
